# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nemraDb
spring.datasource.username=ouahid
spring.datasource.password=nemra2026@@

# JPA
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

# Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=true
spring.flyway.baseline-on-migrate=true
spring.flyway.clean-disabled=true
#spring.flyway.database=postgresql
#spring.flyway.postgresql.transactional.lock=false
#spring.flyway.ignore-unsupported-database=true

# JWT
jwt.secret=9f8e7d6c5b4a3a2f1e0d9c8b7a6f5e4d3c2b1a0987654321
jwt.access-token.expiration=1800000
jwt.refresh-token.expiration=604800000

# Cloudflare
r2.endpoint=https://d8f2022fbc67e0116f7c89eee783c7a0.r2.cloudflarestorage.com
r2.access-key=337f3cb8f9f65d3ebb82792d52a58670
r2.secret-key=c8903f003c8f5b5cfcb97dbe5a9f16818c35ce9164047459a7395f230e911bb3
r2.bucket=nemra-storage
r2.public-url=https://pub-8b8ff1011297433390f5ec33a60bbcd0.r2.dev

#LiveKit
livekit.api-key=devkey
livekit.api-secret=devsecret
livekit.url=ws://localhost:7880

spring.servlet.multipart.max-file-size=2MB